### ISSUE TITLE
Staff Application - (Hyperfire)

### ISSUE THREAD

**Issue by hyperflrers** [flamelands/flamelands#2]
Staff Application
---
**Have you ever been banned before?**

- [ ] Yes
- [x] No

---
**Why do you want to be staff?**
Because i do
---
**What past experience do you have?**
Lots
---
**What skills do you have that will help the community and the staff team?**
Lots
---
**What would you say is your biggest strength?**
Everything
---
**What would you say is your biggest weakness?**
Nothing
---
**Is there anything else you want us to know?**
Nope
---
**What is your username on the network?**
Hyperfire

---

**Comment by HyperfireRS** [comment]
You have been banned for impersonation. This ban will last for 30 days
